### ISSUE TITLE
This relates to all treebanks in universal dependencies

### ISSUE THREAD

**Issue by Eugen2525** [UniversalDependencies/UD_English-LinES#1]
Where can one get SOTA performance for any particular treebank? I think this should be available in the universal dependencies website as the most logical place.

What do you think?

**Comment by martinpopel** [comment]
See http://universaldependencies.org/conll18/results.html#other-rankings (e.g. [LAS for en_lines](http://universaldependencies.org/conll18/results-las.html#en_lines)).
