### ISSUE TITLE
Case=Nom is applied widely beyond pronouns

### ISSUE THREAD

**Issue by nschneid** [UniversalDependencies/UD_English-LinES#17]
In all the other English corpora, only PRON tokens have a `Case` feature. The non-PRON ones listed [here](https://universal.grew.fr/?custom=66f00bac69099) should be fixed, and the [validator settings](https://quest.ms.mff.cuni.cz/udvalidator/cgi-bin/unidep/langspec/specify_feature.pl?lcode=en&feature=Case) updated.

**Comment by LarsAhrenberg** [comment]
Fixed now in dev.

**Comment by nschneid** [comment]
6c2aa64f2159189d086344f735579c238844a98d

Thanks!

**Comment by nschneid** [comment]
Oh but this appears to have introduced some validation issues: http://quest.ms.mff.cuni.cz/udvalidator/cgi-bin/unidep/validation-report.pl?UD_English-LinES

**Comment by LarsAhrenberg** [comment]
Will fix in a couple of days.
