### ISSUE TITLE
"He's" incorrectly split

### ISSUE THREAD

**Issue by AngledLuffa** [UniversalDependencies/UD_English-LinES#7]
There are a few examples of `He's` which is labeled as a `to be` verb, but it's actually `has` and it's been mislabeled

```
# text = He's been waiting for you since eight o'clock.
2       's      be      AUX     PRES    Mood=Ind|Number=Sing|Person=3|Tense=Pres|VerbForm=Fin   4       aux     _       _
```

```
# text = He's been frantic, the woman explained.
2       's      be      AUX     PRES    Mood=Ind|Number=Sing|Person=3|Tense=Pres|VerbForm=Fin   4       aux     _       _
```

```
# text = He's just been to Denmark or somewhere because his mother died.
4       been    be      AUX     PERF    Tense=Past|VerbForm=Part        0       root    _       _
```

```
# text = They tell me he's got the contract for the whole Isoza River reclamation scheme... employs engineers from Poland and Italy
5       's      be      AUX     PRES-AUX        Mood=Ind|Number=Sing|Person=3|Tense=Pres|VerbForm=Fin   6       aux     _       _
```

Hmm, the obvious search would be for `be` that depends on `be`.  Other `VERB` that aren't gerunds are likely to be candidates, as per the last example, but there's also the possibility of a participle being either one, such as `The hurricane's devastated...` vs `AngledLuffa's devastated...`

**Comment by LarsAhrenberg** [comment]
Thanks for spotting this. I will change them for the next release.

**Comment by AngledLuffa** [comment]
I think I got them all in the PR I sent in:

https://github.com/UniversalDependencies/UD_English-LinES/pull/9
